"""Karaoke (word-highlight) ASS builder for dub hardsub export.

Pure text-in/text-out: no ffmpeg, no models, no filesystem. ``build_ass``
turns subtitle cues into an ASS script whose lines carry ``\\k``/``\\kf``
karaoke tags, so ffmpeg's ``ass=`` filter burns a word-by-word highlight
sweep instead of the static line the SRT path renders.

Word timing sources, in order:

1. ``cue["words"]`` — per-word ``{text, start, end}`` persisted at
   transcribe time (services.segmentation). Used only when the words still
   spell the cue's display text: after translation the persisted ASR words
   are source-language tokens, so re-using their timing would burn the
   wrong language. The display text is always authoritative.
2. Even split — the cue text's whitespace tokens spread uniformly across
   ``[start, end]``. This is the compatibility path for jobs transcribed
   before word persistence and for translated tracks.

Dual-layout karaoke is intentionally unsupported (out of scope): callers
must fall back to the line (SRT) burn when the dual layout is requested.
"""

from __future__ import annotations

import re
from typing import Optional, Sequence

_WS = re.compile(r"\s+")

#: Default ASS canvas. libass scales the script to the real video size, so
#: one reference resolution keeps font/margin proportions stable everywhere.
DEFAULT_PLAY_RES = (1920, 1080)

_HEADER_TEMPLATE = """[Script Info]
; Generated by Sesly karaoke burn-in
ScriptType: v4.00+
PlayResX: {res_x}
PlayResY: {res_y}
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,64,&H0000E7FF,&H00FFFFFF,&H00101010,&H7F000000,0,0,0,0,100,100,0,0,1,3,1,2,96,96,48,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _norm(text: object) -> str:
    return _WS.sub(" ", str(text or "").strip())


def _ass_time(seconds: float) -> str:
    """``H:MM:SS.CC`` (centiseconds) — the ASS event timestamp format."""
    cs = max(0, int(round(float(seconds) * 100)))
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, c = divmod(rem, 100)
    return f"{h}:{m:02d}:{s:02d}.{c:02d}"


def _ass_escape(text: str) -> str:
    """Escape a display token for an ASS Dialogue text field.

    Braces would open an override block (user text like ``{\\b1}`` must render
    literally, never execute); newlines become ASS hard line breaks.
    """
    return (
        str(text)
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("\r\n", "\\N")
        .replace("\n", "\\N")
        .replace("\r", "\\N")
    )


def _cs(seconds: float) -> int:
    """Karaoke tag duration in centiseconds; ≥1 so a tag never renders as 0."""
    return max(1, int(round(float(seconds) * 100)))


def even_split_words(text: str, start: float, end: float) -> list[dict]:
    """Uniformly distribute the cue text's whitespace tokens over [start, end].

    The export fallback for jobs transcribed before per-word persistence and
    for translated tracks (whose persisted words are source-language tokens).
    """
    tokens = [tok for tok in _WS.split(str(text or "").strip()) if tok]
    if not tokens:
        return []
    start = float(start)
    dur = max(0.0, float(end) - start) / len(tokens)
    return [
        {"text": tok, "start": start + i * dur, "end": start + (i + 1) * dur}
        for i, tok in enumerate(tokens)
    ]


def scale_words(
    words: Sequence[dict],
    orig_start: float,
    orig_end: float,
    new_start: float,
    new_end: float,
) -> Optional[list[dict]]:
    """Map word times linearly from [orig_start, orig_end] → [new_start, new_end].

    Used when Smart Fit moves a cue onto the fitted timeline: the persisted
    word times live on the original timeline and must ride along. Returns
    ``None`` when either span is degenerate (caller should drop the words so
    export falls back to an even split over the new span).
    """
    orig_span = float(orig_end) - float(orig_start)
    new_span = float(new_end) - float(new_start)
    if orig_span <= 0 or new_span <= 0:
        return None
    ratio = new_span / orig_span
    out: list[dict] = []
    for w in words:
        try:
            ws = float(w["start"])
            we = float(w["end"])
        except (KeyError, TypeError, ValueError):
            return None
        out.append({
            **w,
            "start": round(float(new_start) + (ws - float(orig_start)) * ratio, 3),
            "end": round(float(new_start) + (we - float(orig_start)) * ratio, 3),
        })
    return out


def _usable_words(cue: dict, text: str) -> Optional[list[tuple[str, float, float]]]:
    """Persisted words, iff well-formed AND they spell the cue's display text."""
    words = cue.get("words")
    if not isinstance(words, list) or not words:
        return None
    clean: list[tuple[str, float, float]] = []
    for w in words:
        if not isinstance(w, dict):
            return None
        wtext = _norm(w.get("text"))
        try:
            ws = float(w["start"])
            we = float(w["end"])
        except (KeyError, TypeError, ValueError):
            return None
        if wtext:
            clean.append((wtext, ws, we))
    if not clean:
        return None
    if _norm(" ".join(t for t, _, _ in clean)) != text:
        return None
    return clean


def _karaoke_text(cue: dict, text: str, start: float, end: float) -> str:
    """One Dialogue text field: ``{\\k…}`` lead-in + per-word ``{\\kf…}`` tags.

    Each word's sweep runs until the next word starts (the classic karaoke
    layout — inter-word gaps finish the previous word's fill), and the last
    word sweeps out to the cue end.
    """
    words = _usable_words(cue, text) or [
        (w["text"], w["start"], w["end"]) for w in even_split_words(text, start, end)
    ]
    # Clamp into the cue span and enforce monotonic starts so malformed
    # persisted data can only mistime the sweep, never corrupt the script.
    clamped: list[tuple[str, float]] = []
    prev = start
    for wtext, ws, _ in words:
        ws = min(max(ws, prev), end)
        clamped.append((wtext, ws))
        prev = ws
    parts: list[str] = []
    lead = clamped[0][1] - start
    if lead > 0.005:
        parts.append(f"{{\\k{_cs(lead)}}}")
    for i, (wtext, ws) in enumerate(clamped):
        nxt = clamped[i + 1][1] if i + 1 < len(clamped) else end
        sep = " " if i + 1 < len(clamped) else ""
        parts.append(f"{{\\kf{_cs(max(nxt, ws) - ws)}}}{_ass_escape(wtext)}{sep}")
    return "".join(parts)


def build_ass(
    cues: Sequence[dict],
    *,
    dual: bool = False,
    play_res: tuple[int, int] = DEFAULT_PLAY_RES,
) -> str:
    """Build a karaoke ASS script from subtitle cues ({text, start, end, words?}).

    One ``Default`` style; one Dialogue event per cue. ``dual`` exists for
    signature parity with the line burn but dual-layout karaoke is out of
    scope — callers must keep the SRT line burn for dual, so requesting it
    here is a contract violation, not a rendering mode.
    """
    if dual:
        raise ValueError(
            "dual-layout karaoke is not supported; use the line (SRT) burn for dual subtitles"
        )
    res_x, res_y = play_res
    lines = [_HEADER_TEMPLATE.format(res_x=int(res_x), res_y=int(res_y))]
    for cue in cues or []:
        text = _norm(cue.get("text"))
        if not text:
            continue
        start = float(cue["start"])
        end = float(cue["end"])
        if end <= start:
            end = start + 0.1
        lines.append(
            f"Dialogue: 0,{_ass_time(start)},{_ass_time(end)},Default,,0,0,0,,"
            f"{_karaoke_text(cue, text, start, end)}"
        )
    return "\n".join(lines) + "\n"
